### ISSUE TITLE
HRIT Images

### ISSUE THREAD

**Issue by racerxdl** [sam210723/COMS-1#1]
Hi, so I got curious of that COMS-1 HRIT images and ran over my python library ( https://github.com/opensatelliteproject/xritparser ) - Not sure if you didn't include info because you couldn't find or because you didn't had time but its a 16 bit RAW image from a 10 bit ABI, so I did a small python code to able to covert it raw (I will adapt my xritimg script to be able to dump to jpg/png)

```python
import numpy as np
from PIL import Image
f = open("fd.raw", "rb")
z = np.fromfile(f, dtype=np.uint16,count=2750*2750)
z = z / 4 # Its a 10 bit, so to display in 8 bit you need to divide by 4
img = Image.frombuffer("L", [2750, 2750], z.astype('uint8'), 'raw', 'L', 0, 1)
img.save("fd.png")
```

fd.raw is all the 10 segments data section concatenated.

That way you will get this:
![fd](https://user-images.githubusercontent.com/578310/30012178-17a9f402-9114-11e7-8498-811de6a2d1e1.png)

**Comment by sam210723** [comment]
Perfect, this is exactly where I was stuck with HRIT, I couldn't get the images to behave with ImageMagik. I'll use your code for early HRIT support and to move away from ImageMagik. I should have used PIL in the first place.

I hadn't included my work on HRIT yet because the HRIT downlink is possibly encrypted by KMA, so I put it aside for a while. I won't be able to confirm that until I can get my hands on a dish and feed (soon hopefully). I've mostly been working on map and text overlays.

Thanks heaps for taking a look at HRIT.

**Comment by racerxdl** [comment]
Yeah, PIL makes work easier. 

I did a `xritparse` that read all the headers and print them, that makes easier to detect differences inside the image files. 

Sadly the COMS-1 doesn't strictly follow the LRIT File standard, so some headers seens broken for my xritparse, and so far I know no way to detect that is a COMS-1 lrit file but by the filename.

You might want to check the OSP Map Overlay system, its done for GOES LRIT/HRIT but should give you a way to draw the maps. It is in C# (not in python), but should give you a hint how to proceed:

https://github.com/opensatelliteproject/goesdump/blob/master/XRIT/Geo/MapDrawer.cs
https://github.com/opensatelliteproject/goesdump/blob/master/XRIT/Geo/GeoConverter.cs
https://github.com/opensatelliteproject/goesdump/blob/master/XRIT/Geo/GeoTools.cs
https://github.com/opensatelliteproject/goesdump/blob/master/LibraryTest/Program.cs#L62-L116

**Comment by sam210723** [comment]
I'll take a look at `xritparse` and see if theres a way to distinguish between COMS and GOES xRIT files. If I find anything I'll open an issue over there.

I've been meaning to ask you for some help with the map overlay but those `goesdump` links should answer all my questions.

[lrit-img.py](https://github.com/sam210723/COMS-1/blob/54d04ed9f5ab65a0bd7e9d37d4fdb5d609cd8d32/lrit-img.py#L101-L104) now uses your PIL code to generate a bitmap instead of ImageMagik. I'll work on hrit-img.py integration this evening.

**Comment by racerxdl** [comment]
Sure, let me know if you need any help :D

**Comment by HermioneX** [comment]
hi，I've learned a lot from this  projection,while I got a problem, i saw your data compression type is 0,does this code applicable for files with compression type of Wavelet coded file format( type 1)?Thanks for your reply

**Comment by sam210723** [comment]
I haven't done any work with compression yet since the example data I have is all uncompressed. That will have to wait until I have a dish setup to receive the downlink. Coming soon!
